// Generated by https://quicktype.io

export interface dashboardResponse {
    numberOfOrders:           number;
    paidOrders:               number;
    notPaidOrders:            number;
    numberOfClients:          number;
    numberOfProducts:         number;
    productsWithNotInventory: number;
    lowInventory:             number;
}
